name: Docker Compose CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # This option fetches the submodules

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      run: docker-compose build

    - name: Docker Compose Up
      run: docker-compose up -d

    - name: Run Tests
      run: |
        # Add your test commands here, e.g., check if services are running
        docker ps

    - name: Docker Compose Down
      run: docker-compose down
